#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

#define DEF 0
#define GAM 1
#define LOW 2
#define RAI 3
#define ADJ 4

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [DEF] = LAYOUT(
            KC_GRV , KC_1   , KC_2   , KC_3   , KC_4   , KC_5   ,          KC_6   , KC_7   , KC_8   , KC_9   , KC_0   , QK_BOOT,
            KC_TAB , KC_Q   , KC_W   , KC_E   , KC_R   , KC_T   ,          KC_Y   , KC_U   , KC_I   , KC_O   , KC_P   , KC_LBRC,
            KC_ESC , KC_A   , KC_S   , KC_D   , KC_F   , KC_G   ,          KC_H   , KC_J   , KC_K   , KC_L   , KC_SCLN, KC_QUOT,
            KC_LSFT, KC_Z   , KC_X   , KC_C   , KC_V   , KC_B   ,          KC_N   , KC_M   , KC_COMM, KC_DOT , KC_SLSH, KC_BSPC, 
                                       KC_LCTL, MO(LOW), KC_LALT,          KC_LSFT, MO(RAI), 
                                                KC_LGUI, KC_SPC ,          KC_ENT
    ),
    [GAM] = LAYOUT(
            KC_ESC , KC_1   , KC_2   , KC_3   , KC_4   , KC_5   ,          KC_6   , KC_7   , KC_8   , KC_9   , KC_0   , KC_BSPC,
            KC_TAB , KC_Q   , KC_W   , KC_E   , KC_R   , KC_T   ,          KC_Y   , KC_U   , KC_I   , KC_O   , KC_P   , KC_LBRC,
            KC_LSFT, KC_A   , KC_S   , KC_D   , KC_F   , KC_G   ,          KC_H   , KC_J   , KC_K   , KC_L   , KC_UP  , KC_QUOT, 
            KC_LCTL, KC_Z   , KC_X   , KC_C   , KC_V   , KC_B   ,          KC_N   , KC_M   , KC_COMM, KC_LEFT, KC_DOWN, KC_RGHT,
                                       KC_LCTL, MO(LOW), KC_LALT,          KC_LSFT, MO(RAI), 
                                       KC_LGUI, KC_SPC ,                   KC_ENT
    ),
    [LOW] = LAYOUT(
            _______, KC_F1  , KC_F2  , KC_F3  , KC_F4  , KC_F5  ,          KC_F6  , KC_F7  , KC_F8  , KC_F9  , KC_F10 , KC_F11,
            KC_GRV , KC_EXLM, KC_AT  , KC_HASH, KC_DLR , KC_PERC,          KC_CIRC, KC_AMPR, KC_ASTR, XXXXXXX, XXXXXXX, KC_F12,
            KC_TILD, SNIPING, KC_UNDS, KC_EQL , KC_LT  , KC_GT  ,          KC_LPRN, KC_RPRN, KC_QUOT, KC_DQUO, KC_PIPE, XXXXXXX,
            _______, DRGSCRL, KC_MINS, KC_PLUS, KC_LCBR, KC_RCBR,          KC_LBRC, KC_RBRC, KC_SCLN, KC_COLN, KC_BSLS, _______,
                                       _______, _______, _______,          _______, _______,
                                       _______, _______,                   _______
    ),
    [RAI] = LAYOUT(
            _______, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,          _______, _______, _______, _______, _______, _______,
            _______, KC_1   , KC_2   , KC_3   , KC_4   , KC_5   ,          KC_6   , KC_7   , KC_8   , KC_9   , KC_0   , _______,
            _______, XXXXXXX, XXXXXXX, XXXXXXX, KC_CAPS, KC_RALT,          KC_LEFT, KC_DOWN, KC_UP  , KC_RGHT, DRG_TOG, QK_LOCK,
            _______, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_PSCR,          KC_WBAK, MS_BTN1, MS_BTN2, KC_WFWD, MS_BTN3, _______,
                                       _______, _______, _______,          _______, _______,
                                       _______, _______,                   _______
    ),
    [ADJ] = LAYOUT(
            XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,          XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
            XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,          XXXXXXX, KC_MPRV, KC_MPLY, KC_MNXT, XXXXXXX, XXXXXXX,
            QK_BOOT, XXXXXXX, XXXXXXX, XXXXXXX, DF(DEF), DF(GAM),          XXXXXXX, KC_VOLD, KC_MUTE, KC_VOLU, XXXXXXX, XXXXXXX,
            XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,          XXXXXXX, MS_BTN1, MS_BTN2, XXXXXXX, XXXXXXX, XXXXXXX,
                                       _______, _______, _______,                   _______, _______,
                                       _______, _______,                            _______
    )
};


layer_state_t layer_state_set_user(layer_state_t state) {
    return update_tri_layer_state(state, LOW, RAI, ADJ);
}


#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C


