theme:
  active: "251, 73, 52" # current playing song in list
  banner: "251, 73, 52" # the "spotify-tui" banner on launch
  error_border: "251, 73, 52" # error dialog border
  error_text: "251, 73, 52" # error message text (e.g. "Spotify API reported error 404")
  hint: "250, 189, 47" # hint text in errors
  hovered: "250, 189, 47" # hovered pane border
  inactive: "102, 92, 84" # borders of inactive panes
  playbar_background: "29, 32, 33" # background of progress bar
  playbar_progress: "251, 73, 52" # filled-in part of the progress bar
  playbar_text: "213, 196, 161" # artist name in player pane
  selected: "184, 187, 38" # a) selected pane border, b) hovered item in list, & c) track title in player
  text: "213, 196, 161" # text in panes
