#+TITLE: Emacs Config

Using ~emacs-native-comp-git~ from AUR for improving
performance. Consider running in _daemon mode_, because the startup time
stil not very good.

Speeding up 🐌
- Enabling native compilation
- This sets the garbage collector to invoke every 100Mb instead of default 800Kb
#+begin_src emacs-lisp
(setq comp-deferred-compilation t)
(setq byte-compile-warnings '(cl-functions))
(setq gc-cons-threshold 100000000)
#+end_src
* Main config
** Repositories
There is initializes package mangers and initializing ~use-package~ \\
Package config -- see https://melpa.org/#/getting-started. No more
needed because of managing packages using Nix's home-manager.
#+begin_src emacs-lisp
;; (require 'package)
;; (add-to-list
;;  'package-archives
;;  '("melpa" . "https://melpa.org/packages/")
;;  t)
;; (package-initialize)
;; 
;; (unless (package-installed-p 'use-package)
;;   (package-refresh-contents)
;;   (package-install 'use-package))
#+end_src
Adding folder with manually added packages, loading file private variables
- store all backups in a single directory
#+begin_src emacs-lisp
(add-to-list 'load-path "~/.emacs.d/lisp/")
(load "~/.emacs.d/private.el")
(setq user-init-file "~/.emacs.d/init.el")
(setq backup-directory-alist
      `(("." . ,(concat user-emacs-directory "backups"))))
#+end_src
Extending executable path
#+BEGIN_SRC  emacs-lisp
;; (add-to-list 'exec-path "~/.local/bin")
#+END_SRC
Load nix specific config(mostly for pathes)
#+begin_src emacs-lisp
(load "~/.emacs.d/nix.el")  
#+end_src
* Packages
Speeding up again 🦼
#+begin_src emacs-lisp
(use-package gcmh
  :init
  (gcmh-mode 1))
#+end_src
** Projects
Projects management with ~counsel~ completion
#+begin_src emacs-lisp
(use-package projectile
  :config
  (projectile-mode))
(use-package counsel-projectile)
#+end_src
Support for nix environment variables
#+begin_src emacs-lisp
(use-package direnv
  :config
  (direnv-mode)) 
#+end_src

Amazing git tool
#+begin_src emacs-lisp
(use-package magit)
#+end_src
Project tree. Settings fonts for ~treemacs~
#+begin_src emacs-lisp
(use-package treemacs
  :config
  (dolist (face '(treemacs-root-face
		  treemacs-git-unmodified-face
		  treemacs-git-modified-face
		  treemacs-git-renamed-face
		  treemacs-git-ignored-face
		  treemacs-git-untracked-face
		  treemacs-git-added-face
		  treemacs-git-conflict-face
		  treemacs-directory-face
		  treemacs-directory-collapsed-face
		  treemacs-file-face
		  treemacs-tags-face))
    (set-face-attribute face nil :family "Fira Code" :height 100))
  (setq treemacs-read-string-input 'from-minibuffer)
  )
(use-package treemacs-evil
  :after evil)
(use-package treemacs-projectile
  :after projectile)
#+end_src
** Evil mode
~Evil~ with dependecies. Disable Evil mode for some modes
#+begin_src emacs-lisp
(setq evil-want-keybinding nil)
(use-package goto-chg)
(use-package evil
  :init
  (setq evil-want-integration t)
  :config
  (evil-mode 1)
  (add-to-list 'evil-emacs-state-modes 'elfeed-search)
  (cl-loop for (mode . state) in '((dired-mode . emacs) (elfeed-search . emacs))
	   do (evil-set-initial-state mode state))
  )
(use-package undo-tree
  :config
  (global-undo-tree-mode)
  (evil-set-undo-system 'undo-tree))
#+end_src
Collection of evil keybindings
#+begin_src emacs-lisp
(use-package evil-collection
  :after evil
  :config
  (evil-collection-init))
#+end_src
Fast search
#+begin_src emacs-lisp
(use-package evil-snipe
  :config
  (evil-snipe-mode +1)
  (evil-snipe-override-mode +1))
#+end_src
Change brakets in evil mode
#+begin_src emacs-lisp
(use-package evil-surround
  :config
  (global-evil-surround-mode 1))
#+end_src
Multicursor
#+begin_src emacs-lisp
(use-package evil-multiedit)
(use-package evil-mc
  :config
  (global-evil-mc-mode 1))
#+end_src
** Visual
Icons
#+begin_src emacs-lisp
(use-package all-the-icons
  :config
  (setq all-the-icons-scale-factor 1.0))
#+end_src
HIghlight todo keywords
#+begin_src emacs-lisp
(use-package hl-todo
  :config
  (global-hl-todo-mode t))
#+end_src
Colorize parenthesis
#+begin_src emacs-lisp
(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode))
#+end_src
Searching
#+begin_src emacs-lisp
(use-package avy
  )
#+end_src
Windows hoping
#+begin_src emacs-lisp
(use-package ace-window
  :config
  (setq aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l)))
#+end_src
Dashboard showing on startup
#+begin_src emacs-lisp
(use-package dashboard
  :config
  (dashboard-setup-startup-hook)
  :config
  (setq initial-buffer-choice (lambda () (get-buffer-create "*dashboard*")))
  (setq dashboard-center-content t)
  (setq dashboard-startup-banner "~/Wallpapers/Neofetch.png")
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-items '((recents  . 5)
                                        ;(bookmarks . 5)
                          (projects . 5)
                          (agenda . 5)
                          (registers . 5)))

  )
#+end_src
Highlight lines chaned according to ~git~
#+BEGIN_SRC emacs-lisp
(use-package diff-hl
  :config
  (global-diff-hl-mode)) 
#+END_SRC
*** Themes
~Doom-modeline~ as modeline
#+begin_src emacs-lisp
(use-package doom-modeline
  :init 
  (doom-modeline-mode 1)
  :config
  (setq doom-modeline-icon t))
#+end_src
Colors from pywal
#+begin_src emacs-lisp
(use-package ewal
  :init (setq ewal-use-built-in-always nil
              ewal-use-built-in-on-failure-p t
              ewal-built-in-palette "doom-gruvbox"))
(use-package ewal-doom-themes)
#+end_src
*Or* doom theme
#+begin_src emacs-lisp
(use-package doom-themes
  :preface (defvar region-fg nil)
  (setq doom-themes-treemacs-theme "doom-colors")
  (doom-themes-treemacs-config)
  (doom-themes-org-config)
  :init (load-theme 'doom-molokai t))
#+end_src
*** Settings
- Visual/behaviour
- Dashboard
- y or n instead of yes-or no
- no annoying bell!
- setting ~ace-window~ keys
- isearch
- Treat =_= as work(~vim~ variant)
#+BEGIN_SRC  emacs-lisp
(defun init-hooks () (global-display-line-numbers-mode 1))
(add-hook 'after-init-hook 'init-hooks)
(scroll-bar-mode 0) ; no scroll bar
(tool-bar-mode 0) ; no tool bar
(menu-bar-mode 0) ; no menu bar
(show-paren-mode 1) ; visualize matching parenthesees
(global-hl-line-mode 1) ; highlight current line
(eldoc-mode 1) ; enable docs in minibuffer
(set-face-attribute 'default nil
                    :family "Fira Code"
                    :height 100)
(fset 'yes-or-no-p 'y-or-n-p)
(setq ring-bell-function 'ignore)
(setq case-fold-search t)
(modify-syntax-entry ?_ "w") 
#+end_src
** Keybingings
Convenient keybindings
#+begin_src emacs-lisp
(use-package general)
#+end_src
Constructing menus
#+begin_src emacs-lisp
(use-package hydra)
#+end_src
Keys hints
#+begin_src emacs-lisp
(use-package which-key
  :config
  (which-key-mode 1))
#+end_src
** Programming
Code::stats
#+BEGIN_SRC emacs-lisp
(use-package code-stats
  :config
  (add-hook 'prog-mode-hook #'code-stats-mode)
  (add-hook 'org-mode-hook #'code-stats-mode)
  (run-with-idle-timer 30 t #'code-stats-sync)
  (add-hook 'kill-emacs-hook (lambda () (code-stats-sync :wait)))  
  )
#+END_SRC
Auto parenthesis
#+begin_src emacs-lisp
(use-package smartparens
  :init
  (smartparens-global-mode))
#+end_src
Editconfig support
#+begin_src emacs-lisp
(use-package editorconfig
  :config
  (editorconfig-mode 1))
#+end_src
Snippets
#+begin_src emacs-lisp
(use-package yasnippet
  :init
  (yas-global-mode 1))
(use-package yasnippet-snippets)
#+end_src
Code formatting
#+begin_src emacs-lisp
(use-package format-all)
#+end_src
Dockerfile support
#+BEGIN_SRC emacs-lisp
(use-package dockerfile-mode)
#+END_SRC
Package for html live view
#+begin_src emacs-lisp
(use-package impatient-mode)
#+end_src
Cool web stuff
#+BEGIN_SRC emacs-lisp
(use-package web-mode)
#+END_SRC
*** Auto completion
Use ~company~ for autocompletion. Add snippets to company backends
#+begin_src emacs-lisp
(use-package company
  :init
  (add-hook 'after-init-hook 'global-company-mode)
  :config
  (setq company-dabbrev-downcase 0)
  (setq company-idle-delay 0)
  (setq company-minimum-prefix-length 2)
  (setq company-tooltip-align-annotations t)
  (setq company-auto-commit 'company-auto-commit-p)

  (defun iliayar/company-complete-selection ()
    "Insert the selected candidate or the first if none are selected."
    (interactive)
    (if company-selection
        (company-complete-selection)
      (company-complete-number 1)))
  ;; (setq company-frontends '(company-pseudo-tooltip-frontend
  ;; 			    company-echo-metadata-frontend))
  (setq company-backends 
        '(company-capf 
          ;; company-bbdb 
          ;; company-clang 
          ;; company-keywords 
          company-yasnippet 
          ;; company-lsp 
          ;; company-files 
          ;; company-ctags
          ;; company-anaconda
          ))

  (defun mars/company-backend-with-yas (backends)
    "Add :with company-yasnippet to company BACKENDS.
  Taken from https://github.com/syl20bnr/spacemacs/pull/179."
    (if (and (listp backends) (memq 'company-yasnippet backends))
        backends
      (append (if (consp backends)
                  backends
                (list backends))
              '(:with company-yasnippet))))

  (defun add-yas-in-company ()
    (setq company-backends
          (mapcar #'mars/company-backend-with-yas company-backends)))

  (add-yas-in-company)

  (setq company-math-allow-latex-symbols-in-faces t)
  )
#+end_src
Lsp ~backend~ for ~company~
#+begin_src emacs-lisp
;; (use-package company-lsp
;;   :after lsp-mode
;;   :config
;;   (push 'company-lsp company-backends)
;;   (setq company-lsp-enable-snippet t)
;;   (setq lsp-enable-snippet t))
#+end_src
Display completion in child buffer, quite slow 😞
#+BEGIN_SRC emacs-lisp
;; (use-package company-posframe
;;   :config
;;   (company-posframe-mode 1))
#+END_SRC
Completion for =M-x= commands. Enabling ~counsel-colors-emacs~.
#+begin_src emacs-lisp
(use-package counsel
  :init
  (ivy-mode 1)
  :config
  (require 'facemenu)
  :config
  (setq projectile-completion-system 'ivy)
  (setq ivy-use-selectable-prompt t)
  (setq ivy-initial-inputs-alist nil)
  )
#+end_src
*** Languages and lsp
Nix, and completion
#+begin_src emacs-lisp
(use-package nix-mode
  :mode "\\.nix\\'") 
(use-package nixos-options)
(use-package company-nixos-options)
#+end_src

Lsp client. Speeding up 🛹, adding folders to not track. \\
Add to hook =(XXX-mode . lsp)= for auto enabling lsp on /XXX-mode/
#+begin_src emacs-lisp
(use-package  lsp-mode
  :hook (
         (lsp-mode . lsp-enable-which-key-integration) 
         (c++-mode . lsp)
         )
  :config
  (setq read-process-output-max (* 4 (* 1024 1024)))
  (setq lsp-file-watch-ignored
        '("build"
          "out"
          "target"
          "release"
          ".git"
          ))
  (setq lsp-log-io nil)
  (setq lsp-idle-delay 0.500))
#+end_src
Syntax checking and lsp related errors/warnings. Posfrmae stil sucks
#+BEGIN_SRC emacs-lisp
(use-package flycheck)
;; (use-package flycheck-posframe
;;   :hook (flycheck-mode . flycheck-posframe-mode))
#+END_SRC
Lsp integration with several plugins
#+begin_src emacs-lisp
(use-package lsp-treemacs)
(use-package lsp-ivy)
#+end_src
C++ lsp \\
In /build/ directory run =cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=YES ..=
#+BEGIN_SRC emacs-lisp
(use-package ccls
  :config
  (setq ccls-executable "/usr/bin/ccls")
  (setq ccls-initialization-options
        '(:compilationDatabaseDirectory "build"
                                        :cache (:directory "build/.ccls-cache"))))
#+END_SRC
Haskell lsp
#+begin_src emacs-lisp
(use-package lsp-haskell)
#+end_src
Python lsp
#+begin_src emacs-lisp
(use-package lsp-pyright
  :hook (python-mode . (lambda ()
                         (require 'lsp-pyright)
                         (lsp))))  ; or lsp-deferred
(use-package anaconda-mode)
(use-package company-anaconda)
#+end_src
emacs ipython notebook
#+begin_src emacs-lisp
(use-package ein)
#+end_src
Lsp for latex
#+begin_src emacs-lisp
(use-package lsp-latex)
#+end_src
Rust mode
#+begin_src emacs-lisp
(use-package rustic)
#+end_src
Go mode
#+begin_src emacs-lisp
(use-package go-mode)
#+end_src
Haskell mode
#+begin_src emacs-lisp
(use-package haskell-mode)
#+end_src
Yaml files
#+begin_src emacs-lisp
(use-package yaml-mode)
#+end_src
Kotlin
#+BEGIN_SRC emacs-lisp
(use-package kotlin-mode)
#+END_SRC
Graphviz
#+BEGIN_SRC emacs-lisp
(use-package graphviz-dot-mode)
#+END_SRC
Ipython for org babel
#+BEGIN_SRC emacs-lisp
(use-package ob-ipython)
#+END_SRC
Java lsp
#+BEGIN_SRC emacs-lisp
(use-package lsp-java)
#+END_SRC
*** Settings
- C style settings
- Scrool compilation buffer to the first error instead of end.
#+BEGIN_SRC emacs-lisp
(setq c-default-style "linux")
(setq compilation-scroll-output 'first-error)
#+END_SRC
** Org-mode
theoremes in LaTeX with org syntax
#+begin_src emacs-lisp
(use-package org-special-block-extras
  ;; :hook (org-mode . org-special-block-extras-mode)
  :config (org-special-block-extras-short-names))
#+end_src
Reveal.js for presentations
#+BEGIN_SRC emacs-lisp
;; (use-package ox-reveal
;;   :config
;;   (setq org-reveal-root (expand-file-name "~/.local/share/reveal.js-4.1.0")))
#+END_SRC
Export Org mode to Json
#+BEGIN_SRC emacs-lisp
(use-package ox-json)
#+END_SRC
Org headers icons
#+begin_src emacs-lisp
(use-package org-bullets)
#+end_src
Loading Export backends
#+BEGIN_SRC emacs-lisp
(require 'ox-rss)
(eval-after-load "org"
  (progn
    '(require 'ox-md nil t)
    '(require 'ox-rss nil t)
    '(require 'ox-latex nil t)
    '(require 'ox-json nil t)
    '(require 'ox-reveal nil t)))
#+end_src
Org Roam
#+BEGIN_SRC emacs-lisp
(use-package org-roam
  :init
  (setq org-roam-v2-ack t)
  :custom
  (org-roam-directory "~/org/roam")
  :bind (("C-c n l" . org-roam-buffer-toggle)
	 ("C-c n f" . org-roam-node-find)
	 ("C-c n i" . org-roam-node-insert)
	 ("C-c n d" . org-roam-dailies-capture-today)
	 :map org-mode-map
	 ("C-M-i" . completion-at-point))
  :config
  (setq org-roam-completion-everywhere t)
  (setq org-roam-dailies-direcory "journal/")
  (org-roam-setup))
(use-package websocket)

(load-library "org-roam-ui")
#+END_SRC
*** Settings
Setting visual stuff
#+begin_src emacs-lisp
(setq-default prettify-symbols-alist '(("#+begin_src" . "↓")
                                       ("#+end_src" . "↑")
                                       ("#+BEGIN_SRC" . "↓")
                                       ("#+END_SRC" . "↑")
                                       ("#+end_proof" . "⬜")
                                       ("[ ]" . "")
                                       ("[X]" . "")
                                       ("[-]" . "")
                                       ))

(setq org-hide-emphasis-markers t
      org-fontify-done-headline t
      org-ellipsis "⤶"
      org-pretty-entities t
      prettify-symbols-unprettify-at-point 'right-edge
      org-directory "~/org"
      org-agenda-files '("~/org")
      org-default-notes-file (concat org-directory "/Notes.org")
      org-highlight-latex-and-related '(latex entities)
      org-todo-keywords '((sequence "DRIFTED" "TODO" "FIXME" "|" "DONE" "CANCELED" ))
      org-src-preserve-indentation t)

(setq org-todo-keyword-faces
      '(("TODO"     . "magenta")
        ("FIXME"    . "red")
        ("DONE"     . "LawnGreen")
        ("DRIFTED"  . "DeepSkyBlue1")
        ("CANCELED" . "yellow2")))

(font-lock-add-keywords 'org-mode
                        '(("^ *\\([-]\\) "
                           (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))
#+end_src
Defining action to execute at entering org-mode, disable marking capture entry as bookmark
#+begin_src emacs-lisp
(add-hook 'org-mode-hook 
          (lambda () 
            (org-bullets-mode 1)
            (org-indent-mode nil)
            (prettify-symbols-mode)
            (set-fontset-font t 'symbol "Noto Color Emoji")
            (progn
              (setq left-margin-width 5)
              (setq right-margin-width 5)
              (set-window-buffer nil (current-buffer)))))

(setq org-capture-bookmark nil)
#+END_SRC
Increse readability of latex preview in org-mode
#+begin_src emacs-lisp
(setq org-format-latex-options (plist-put org-format-latex-options :scale 2.0))
#+end_src
Org mode file associations
#+BEGIN_SRC emacs-lisp
(setq org-file-apps
      (append '(
                ("\\.pdf\\'" . "zathura %s")
                ) org-file-apps ))
#+END_SRC
- Add /dot/ to org-babel
- Enable redisplaying images after executing block
- Auto confirm evaluating /dot/
#+BEGIN_SRC emacs-lisp
(add-to-list 'org-src-lang-modes (quote ("dot" . graphviz-dot)))
(org-babel-do-load-languages
 'org-babel-load-languages
 '((dot . t)
   (gnuplot . t)
   (org . t)
   (python . t)
   (js . t)
   (shell . t)
   (ipython . t)))
(add-hook 'org-babel-after-execute-hook 'org-redisplay-inline-images)
(setq org-confirm-babel-evaluate nil)
(setq org-src-tab-acts-natively t)
#+END_SRC
Export settings
#+BEGIN_SRC emacs-lisp
(setq org-html-htmlize-output-type 'inline-css)
(setq org-html-head-include-default-style nil)
#+END_SRC
Setting up spell checking. Working for both laguages, but only one in one buffer.
#+BEGIN_SRC emacs-lisp
(with-eval-after-load "ispell"
  (setq ispell-program-name "hunspell")
  (setq ispell-dictionary "ru_RU,en_US")
  (ispell-set-spellchecker-params)
  (ispell-hunspell-add-multi-dic "ru_RU,en_US"))
#+END_SRC
Inserting last screenshot
#+BEGIN_SRC emacs-lisp
(defun my/org-insert-last-screenshot ()
  (interactive)
  (setq screenshots-dir "~/Pictures/screenshots/")
  (let ((cur-dir (read-directory-name "Copy screenshot to: "))
        (screenshot (car (last (directory-files screenshots-dir)))))
    (copy-file (concat screenshots-dir screenshot) (concat cur-dir screenshot) t)
    (org-insert-link nil (concat cur-dir screenshot)))
  (org-redisplay-inline-images))
#+END_SRC
Set Org-mode exporting backends
#+BEGIN_SRC emacs-lisp
(setq org-export-backends '(ascii html icalendar latex md odt))
#+END_SRC
*** Publishing
Publishing for:
- Main site
- University consepcts (exporting to pdf and uploading on server)
#+BEGIN_SRC emacs-lisp
(defun my-conspects-header (arg)
  "<style>#forkongithub a{background:#000;color:#fff;text-decoration:none;font-family:arial,sans-serif;text-align:center;font-weight:bold;padding:5px 40px;font-size:1rem;line-height:2rem;position:relative;transition:0.5s;}#forkongithub a:hover{background:#c11;color:#fff;}#forkongithub a::before,#forkongithub a::after{content:\"\";width:100%;display:block;position:absolute;top:1px;left:0;height:1px;background:#fff;}#forkongithub a::after{bottom:1px;top:auto;}@media screen and (min-width:800px){#forkongithub{position:fixed;display:block;top:0;right:0;width:200px;overflow:hidden;height:200px;z-index:9999;}#forkongithub a{width:200px;position:absolute;top:60px;right:-60px;transform:rotate(45deg);-webkit-transform:rotate(45deg);-ms-transform:rotate(45deg);-moz-transform:rotate(45deg);-o-transform:rotate(45deg);box-shadow:4px 4px 10px rgba(0,0,0,0.8);}}</style><span id=\"forkongithub\"><a href=\"https://github.com/iliayar/ITMO\">Fork me on GitHub</a></span>")

(setq org-publish-project-alist
      '(
        ("org-mainsite"
         :base-directory "~/Documents/MainSite/public/notes"
         :base-extension "org"
         :exclude "level-[0-9]*.org"
         :publishing-directory "/ssh:iliayar@iliayar.ru:/var/www/mainsite/public/public-notes"
         :html-html5-fancy t
         ;; :html-link-home "https://iliayar.ru/public-notes/index.html"
         :html-validation-link nil
         :html-postamble "<hr><a href=\"/public-notes/index.html\">Home Page</a><span style=\"float: right\"><a href=\"/public-notes/blog.xml\"><i class=\"fas fa-rss\"></i></a> <a href=\"https://github.com/iliayar/iliayar\"><i class=\"fab fa-github\"></i></a></span>"
         :recursive t
         :publishing-function org-html-publish-to-html
         :headline-levels 4             ; Just the default for this project.
         :auto-preamble t
         )
        ("rss-mainsite"
         :base-directory "~/Documents/MainSite/public/notes"
         :base-extension "org"
         :exclude ".*"
         :include ("blog.org")
         :publishing-directory "/ssh:iliayar@iliayar.ru:/var/www/mainsite/public/public-notes"
         :rss-extension "xml"
         :section-numbers nil
         :html-link-home "https://iliayar.ru/public-notes/"
         :html-link-use-abs-url t
         :html-link-org-files-as-html t
         :output-file "rss"
         :recursive nil
         :publishing-function org-rss-publish-to-rss
         )
        ("static-mainsite"
         :base-directory "~/Documents/MainSite/public/notes"
         :base-extension "css\\|js\\|png\\|jpg\\|gif\\|pdf\\|mp3\\|ogg\\|swf\\|pdf"
         :publishing-directory "/ssh:iliayar@iliayar.ru:/var/www/mainsite/public/public-notes"
         :recursive t
         :publishing-function org-publish-attachment
         )
        ("mainsite" :components ("org-mainsite" "rss-mainsite" "static-mainsite"))

        ("org-conspects"
         :base-directory "~/Documents/ITMO"
         :exclude ".*[^E].org"
         :publishing-directory "/ssh:iliayar@iliayar.ru:/var/www/mainsite/public/public-notes/conspects"
         :recursive t
         :html-postamble "<hr><a href=\"/public-notes/index.html\">Home Page</a><span style=\"float: right\"><a href=\"https://t.me/iliayar\"><i class=\"fab fa-telegram-plane\"></i></a> <a href=\"https://github.com/iliayar/ITMO\"><i class=\"fab fa-github\"></i></a></span><br><a href=\"/public-notes/conspects/README.html\">Conspects Home Page</a>"
         :publishing-function org-html-publish-to-html
         :headline-levels 4             ; Just the default for this project.
         ;; :html-preamble my-conspects-header
         )
        ("pdfs-conspects"
         :base-directory "~/Documents/ITMO"
         :base-extension "org"
         :exclude "README.org\\|level-[0-9]*.org\\|level-subj.org"
         :publishing-directory "/ssh:iliayar@iliayar.ru:/var/www/mainsite/public/public-notes/conspects"
         :recursive t
         :publishing-function org-latex-publish-to-pdf
         )
        ("conspects" :components ("org-conspects" "pdfs-conspects"))
        ))
#+END_SRC
*** LaTeX
Org mode to LaTeX and pdf
Setting packages
#+BEGIN_SRC emacs-lisp
(setq org-latex-packages-alist '(
                                 ("T1, T2A" "fontenc" t)
                                 ("lutf8" "luainputenc" t)
                                 ("english,russian" "babel" t)
                                 ("" "minted" t)
                                 ("" "graphicx" t)
                                 ("" "longtable" t)
                                 ("" "hyperref" t)
                                 ("" "xcolor" t)
                                 ("" "natbib" t)
                                 ("" "amssymb" t)
                                 ("" "stmaryrd" t)
                                 ("" "amsmath" t)
                                 ("" "caption" t)
                                 ("" "mathtools" t)
                                 ("" "amsthm" t)
                                 ("" "tikz" t)
                                 ("" "fancyhdr" t)
                                 ("" "lastpage" t)
                                 ("" "titling" t)
                                 ("" "grffile" t)
                                 ("" "extarrows" t)
                                 ("" "wrapfig" t)
                                 ("" "algorithm" t)
                                 ("" "algorithmic" t)
                                 ("" "lipsum" t)
                                 ("" "rotating" t)
                                 ("" "placeins" t)
                                 ("normalem" "ulem" t)
                                 ("" "amsmath" t)
                                 ("" "textcomp" t)
                                 ("" "svg" t)
                                 ("" "capt-of" t)))
;; Reset default value. For debugging
(custom-reevaluate-setting 'org-latex-classes)
(with-eval-after-load 'ox-latex
  (progn 
    (add-to-list 'org-latex-classes
                 (list "general"
                       "
  \\documentclass[english]{article}
  [NO-DEFAULT-PACKAGES]
  [PACKAGES]
  [EXTRA]
  \\usepackage{geometry}
  \\geometry{a4paper,left=2.5cm,top=2cm,right=2.5cm,bottom=2cm,marginparsep=7pt, marginparwidth=.6in}
  \\input{~/.emacs.d/preamble.sty}
  "
                       '("\\section{%s}" . "\\section*{%s}")
                       '("\\subsection{%s}" . "\\subsection*{%s}")
                       '("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                       '("\\paragraph{%s}" . "\\paragraph*{%s}")
                       '("\\subparagraph{%s}" . "\\subparagraph*{%s}")
                       ))
    (add-to-list 'org-latex-classes
                 (list "lectures"
                       "
  \\documentclass[oneside]{book}
  [NO-DEFAULT-PACKAGES]
  [PACKAGES]
  [EXTRA]
  \\addto\\captionsrussian{\\renewcommand{\\chaptername}{Лекция}}
  \\renewcommand{\\leftmark}{}
  \\usepackage[a4paper, total={6in, 8in}]{geometry}
  \\input{~/.emacs.d/preamble.sty}
  \\fancyhead[L]{\\leftmark}
  "
                       '("\\chapter*{%1$s}\\renewcommand{\\leftmark}{%1$s}\\addcontentsline{toc}{chapter}{%1$s}\\stepcounter{chapter}" . "\\chapter{%s}")
                       '("\\section{%s}" . "\\section*{%s}")
                       '("\\subsection{%s}" . "\\subsection*{%s}")
                       '("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                       '("\\paragraph{%s}" . "\\paragraph*{%s}")
                       '("\\subparagraph{%s}" . "\\subparagraph*{%s}")
                       ))))
(setq org-latex-listings 'minted
      org-latex-pdf-process
      '("pdflatex -shell-escape --synctex=1 -interaction nonstopmode -output-directory %o %f"
        "pdflatex -shell-escape --synctex=1 -interaction nonstopmode -output-directory %o %f"
        "pdflatex -shell-escape --synctex=1 -interaction nonstopmode -output-directory %o %f"))
(setq org-latex-minted-options
      '(("frame" "lines") ("linenos=true") ("mathescape")))
(add-to-list 'org-latex-minted-langs '(ipython "python"))
#+END_SRC
** Common
RSS reader. Settings colors for each tag.
#+begin_src emacs-lisp
(use-package elfeed
  :custom
  (rmh-elfeed-org-files (list "~/org/elfeed.org"))
  :config
  (defface unread-tag-face '((t :foreground "light grey")) "Marks unread")
  (defface news-tag-face '((t :foreground "light yellow")) "Mark news")
  (defface ctf-tag-face '((t :foreground "red")) "Mark CTF events")
  (defface blog-tag-face '((t :foreground "cyan")) "Mark posts")
  (defface github-tag-face '((t :foreground "orange")) "Mark Github feed")
  (defface starred-tag-face '((t :foreground "yellow")) "Mark favourite posts")
  (defface videos-tag-face '((t :foreground "tomato")) "Mark favourite posts")
  (setq elfeed-search-face-alist
        '(
          (starred starred-tag-face)
          (ctf ctf-tag-face)
          (blog blog-tag-face)
          (news news-tag-face)
          (github github-tag-face)
          (videos videos-tag-face)
          (unread elfeed-search-unread-title-face)
          ))

  (defalias 'elfeed-toggle-star
    (elfeed-expose #'elfeed-search-toggle-all 'starred))
  )
(use-package elfeed-org
  :init
  (elfeed-org))
(use-package elfeed-goodies
  :init
  (elfeed-goodies/setup))
#+end_src
Mail client
#+BEGIN_SRC emacs-lisp
(use-package mu4e
  :ensure nil
  :config
  (setq user-full-name "Ilya Yaroshevskiy")
  
  (setq mu4e-change-filenames-when-moving t)
  (setq mu4e-update-interval (* 10 60))
  (setq mu4e-maildir "~/Mail")
  (setq mu4e-headers-skip-duplicates t)
  (setq mu4e-attachment-dir "~/Downloads")
  (setq mu4e-sent-messages-behavior 'delete)
  (setq mu4e-use-fancy-chars t)
  (setq message-send-mail-function 'smtpmail-send-it)
  (setq mu4e-completing-read-function 'ivy-completing-read)

  (setq mu4e-contexts
        (list
         ;; Personal context
         (make-mu4e-context
          :name "personal"
          :match-func (lambda (msg) (when msg
                                      (string-prefix-p "/personal" (mu4e-message-field msg :maildir))))
          :vars '((mu4e-sent-folder . "/personal/[Gmail]/Sent Mail")
                  (mu4e-drafts-folder . "/personal/[Gmail]/Drafts")
                  ;; (mu4e-refile-folder . "/personal/[Gmail]/All Mail")
                  (mu4e-trash-folder . "/personal/[Gmail]/Trash")
                  (user-mail-address . "iliayar3@gmail.com")
                  (mu4e-get-mail-command . "mbsync personal")
                  (smtpmail-smtp-server . "smtp.gmail.com")
                  (smtpmail-smtp-service . 465)
                  (smtpmail-stream-type . ssl)
                  (smtpmail-smtp-user . "iliayar3@gmail.com")
                  (mu4e-bookmarks . (("maildir:/personal/Inbox" "Inbox" ?i)
                                     ("maildir:/personal/[Gmail]/Important" "Important" ?!)))
                  ))
         ;; Cock context
         (make-mu4e-context
          :name "cock"
          :match-func (lambda (msg) (when msg
                                      (string-prefix-p "/cock" (mu4e-message-field msg :maildir))))
          :vars '(
                  (mu4e-sent-folder . "/cock/Sent")
                  ;; (mu4e-drafts-folder . "/cock/Drafts")
                  (mu4e-refile-folder . "/cock/Junk")
                  (mu4e-trash-folder . "/cock/Trash")
                  (user-mail-address . "iliayar@cock.li")
                  (mu4e-get-mail-command . "mbsync cock")
                  (smtpmail-smtp-server . "mail.cock.li")
                  (smtpmail-smtp-service . 465)
                  (smtpmail-stream-type . ssl)
                  (smtpmail-smtp-user . "iliayar@cock.li")
                  (mu4e-bookmarks . (("maildir:/cock/Inbox" "Inbox" ?i)
                                     ;; ("maildir:/personal/[Gmail]/Important" "Important" ?!)
                                     ))
                  ))
         )))
#+END_SRC

* Keybindings
Evil!
#+BEGIN_SRC emacs-lisp
(define-minor-mode my-override-mode
  "Overrides all major and minor mode keys" t)

(defvar my-override-map (make-sparse-keymap "my-override-map")
  "Override all major and minor mode keys")

(add-to-list 'emulation-mode-map-alists
             `((my-override-mode . ,my-override-map)))

(define-key my-override-map (kbd "<left>")
  (lambda ()
    (interactive)
    (message "Use Vim keys: h for Left")))

(define-key my-override-map (kbd "<right>")
  (lambda ()
    (interactive)
    (message "Use Vim keys: l for Right")))

(define-key my-override-map (kbd "<up>")
  (lambda ()
    (interactive)
    (message "Use Vim keys: k for Up")))

(define-key my-override-map (kbd "<down>")
  (lambda ()
    (interactive)
    (message "Use Vim keys: j for Down")))
(evil-make-intercept-map my-override-map) 
#+END_SRC
#+begin_src emacs-lisp
(general-define-key
 :keymaps 'company-active-map
 "<tab>"     'yas-expand
 "<backtab>" 'iliayar/company-complete-selection)

(general-define-key
 "M-x" 'counsel-M-x)

(general-define-key
 :map 'org-mode-map
 "C-c C-x i" 'my/org-insert-last-screenshot)

(define-key isearch-mode-map (kbd "<down>") 'isearch-ring-advance)
(define-key isearch-mode-map (kbd "<up>") 'isearch-ring-retreat)
#+end_src
Elfeed hydra binddings
#+begin_src emacs-lisp
(defhydra elfeed-search-view-hydra (:color blue :hint t)
  ("d" (elfeed-search-set-filter nil) "Default")
  ("f" (elfeed-search-set-filter "+starred") "Favourite")
  ("a" (elfeed-search-set-filter "") "All"))
#+end_src
Bindings using ~general~ package
#+begin_src emacs-lisp
(general-define-key
 :state '(normal)
 :keymaps '(org-mode-map)
 "<tab>" 'org-cycle)
(general-define-key
 :states '(normal visual emacs insert treemacs)
 :prefix "SPC"
 :non-normal-prefix "M-SPC"
 :keymaps 'override
 "bf" 'counsel-switch-buffer
 "bb" 'ibuffer
 "ca" 'lsp-execute-code-action
 "cc" 'compile
 "cd" 'kill-compilation-buffer
 "cf" 'counsel-grep-or-swiper
 "cl" 'comment-or-uncomment-region
 "cr" 'lsp-rename
 "ff" 'counsel-find-file
 "gl" 'avy-goto-line
 "gr" 'revert-buffer
 "gs" 'avy-goto-char-timer
 "oa" 'org-agenda
 "og" 'magit
 "or" 'elfeed
 "op" 'treemacs
 "om" 'mu4e
 "pc" 'projectile-compile-project
 "pf" 'counsel-projectile-find-file
 "pp" 'projectile-switch-project
 "rr" 'rustic-cargo-run
 "sl" 'lsp
 "sr" 'lsp-workspace-restart
 "ss" 'lsp-workspace-shutdown
 "tt" 'treemacs-select-window
 "wd" 'delete-window
 "wk" 'kill-buffer-and-window
 "wr" 'hydra-window-resize-menu/body
 "ww" 'ace-window)

(general-define-key
 :states '(visual)
 :keymaps 'override
 "R"  'evil-multiedit-match-all
 )

(general-define-key
 :states '(normal visual insert)
 :prefix "SPC"
 :non-normal-prefix "M-SPC"
 :keymaps 'latex-mode-map
 "si" 'latex-insert-block
 )

(general-define-key
 :keymaps 'elfeed-search-mode-map
 "f" 'elfeed-toggle-star
 "v" 'elfeed-search-view-hydra/body)
#+end_src
Hydra
#+begin_src emacs-lisp
(defhydra hydra-window-resize-menu (:color red
                                           :hint nil)
  "
    Window Resize
    -------------
         /\\
          _k_
    < _h_     _l_ >
          _j_
          v
    "
  ("h" evil-window-decrease-width)
  ("l" evil-window-increase-width)
  ("k" evil-window-decrease-height)
  ("j" evil-window-increase-height)
  ("c" nil "Cancel"))
#+end_src

