# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ pkgs.systec-can ];
  hardware.firmware = [ pkgs.systec-can ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8ffa31d5-c06a-4c8b-af3f-8f5c635724b3";
      fsType = "ext4";
      neededForBoot = true;
    };

  boot.initrd.luks.devices."cryptroot" =
    {
      device = "/dev/disk/by-uuid/a9cee7c3-ba8e-42d0-ac8d-24ee23be55c5";
    };


  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A9E3-2619";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/cf4af9e2-b3a1-49be-8f95-f7d6164baa15";
      encrypted = {
        enable = true;
        label = "crypthome";
        blkDev = "/dev/disk/by-uuid/2ebb75d6-d220-42ed-b731-d5b76ed67d20";
        keyFile = "/mnt-root/etc/keyfiles/crypthome";
      };
      fsType = "ext4";
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
