on: 
  push:
    branch:
      - master

name: 'Shellcheck'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Installing shellcheck
      run: |
        apt-get update; apt-get install shellcheck
