name: CI

on:
  push:
    branches: [ master ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Shell Linter
        uses: azohra/shell-linter@v0.4.0
        with:
          path: ./install.sh
