resolver: lts-16.6

packages:
- xmobar-git
- xmonad-git
- xmonad-contrib-git
extra-deps:
- iwlib-0.1.0
- netlink-1.1.1.0
- libmpd-0.10.0.0
- X11-1.10

flags:
  xmobar:
    all_extensions: true
  xmonad-contrib:
      use_xft: true
