[package]
name = "rust-blocks"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unix-named-pipe = "0.2.0"
tokio = { version = "1.9.0", features = [ "full" ] }
async-trait = "0.1.50"
futures = "0.3.16"
dbus = "0.9.3"
dbus-tokio = "0.7.3"
notify-rust = "4.5.2"
